apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-microservices-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/LexmarkCS/Lexmark.git'  # Git repo
    targetRevision: HEAD
    path: overlays/dev  # Path to the dev overlay
    kustomize:
      namePrefix: my-app-  # Prefix for all resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default  # Namespace in which to deploy the app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
