apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
  # annotations:
    # Image list to track updates for the following images
    # argocd-image-updater.argoproj.io/image-list: |
    #   uiservice=docker.io/lexmarkkubernetes/uiservice
    #   apiservice=docker.io/lexmarkkubernetes/apiservice
    #   db_microservice=docker.io/lexmarkkubernetes/db_microservice
    # argocd-image-updater.argoproj.io/refresh: always
    # argocd-image-updater.argoproj.io/apiservice.update-strategy: "latest"  # Or "semver"
    # argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/lexmarkCS499/Lexmark.git'  # Git repo
    targetRevision: staging
    path: overlays/staging  # Path to the dev overlay
    # kustomize:
    #   namePrefix: dev-  # Prefix for all resources
  destination:
    server: 'https://kubernetes.default.svc'  
    namespace: staging  # Namespace in which to deploy the app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
